baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "pt-br"

title: "H4I"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "H4I"
  description: "Hub of New Digital Technologies for Industry."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "Â© 2024 H4I  All Rights Reserved"

menus:
  main:
    - name: "H4i"
      url: "/#hero"
      weight: 1

    - name: "Linhas de Pesquisa"
      url: "/#services"
      weight: 2

    - name: "Pesquisadores"
      url: "/#team"
      weight: 3

    - name: "Cursos"
      url: "/#portifolio"
      weight: 4

    - name: "Noticias"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Contato"
      url: "/#"
      weight: 6
      pre: "btn btn-primary text-light"

  footer:
    - name: "H4i"
      url: "/#hero"
      weight: 1

    - name: "Linhas de Pesquisa"
      url: "/#services"
      weight: 2

    - name: "Pesquisadores"
      url: "/#team"
      weight: 3

    - name: "Cursos"
      url: "/#portifolio"
      weight: 4

    - name: "Noticias"
      url: "/blog"
      weight: 5


taxonomies:
  series: "series"
  tags: "tags"
